### ISSUE TITLE
Vibrato value moves continuously

### ISSUE THREAD

**Issue by alexlevacher** [Enhancia/Plume-Public#20]
**Description**
The vibrato value twitches which assigns it inside the DAW
Solution : cut non significative changes so that the value only updates when the ring actually moves.
Also happens for the tilt/roll/pb, but less problematic

**infos**
OS:
Plume version:

**Comment by leboulda** [comment]
Up, corrigé pour le vibrato intensity mais pas sur le Roll et tilt

**Comment by leboulda** [comment]
Toujours un peu la merde, mais on va changer la manière dont les paramètres sont gérés donc balek
